### ISSUE TITLE
Tasks todo

### ISSUE THREAD

**Issue by HosenNaser** [HosenNaser/team2#1]
1. Create files

- [ ] Index.html
- [ ] Style.scss
- [ ] Signin.html
- [ ] Signup.html
- [ ] Dashboard.html
- [ ] ForgetPassword.html
- [ ] renewPassword.html
- [ ] readme

2.  Create index.html

- [ ] html code
- -[ ] loading animation
- -[ ] connect signin.js

3. Create Sign in

- [ ] build html code
- [ ] build CSS style
- - [ ] web 
- - [ ] phone
- [ ] build JS code 
- - [ ] check database users 
- - [ ] check signed in user  
- - [ ] set cookies 
- - [ ] reroute to dashboard

4. Create sign up

- [ ] build html code
- [ ] build CSS style
- - [ ] web 
- - [ ] phone
- [ ] build JS code 
- - [ ] User validation or existing 
- - [ ] Email validation or existing 
- - [ ] Password validation 
- - [ ] set cookies 
- - [ ] reroute to dashboard

5. Create forgot password 

- [ ] build html code
- [ ] build CSS style
- - [ ] web 
- - [ ] phone
- [ ] build JS code 
- - [ ] check email if exist in database
- - [ ]  reroute to renew password page

6. Create Dashboard 
- [ ] build html code
- [ ] build CSS style
- - [ ] web 
- - [ ] phone
- [ ] build JS code 
- - [ ] logout function 
- - [ ] clear cookies after logging out 

7. Create renew password
- [ ] build html code
- [ ] build CSS style
- - [ ] web 
- - [ ] phone
- [ ] build JS code 
- - [ ] renew the password in database
- - [ ] reroute to dashboard 
- - [ ] enter user data to cookies
